version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fLex9bDK9VUyKgUa
      MYSQL_DATABASE: asso-blog
      MYSQL_USER: asso-blog
      MYSQL_PASSWORD: JvvCxqkHT4Jmz79U
  wordpress:
    depends_on:
      - db
    image: asso-blog-c:latest
    ports:
      - "3000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      MYSQL_DATABASE: asso-blog
      MYSQL_USER: asso-blog
      MYSQL_PASSWORD: JvvCxqkHT4Jmz79U