version: '3'
services:
  db:
    image: mysql:8
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fLex9bDK9VUyKgUa
      MYSQL_DATABASE: asso-blog
      MYSQL_USER: asso-blog
      MYSQL_PASSWORD: JvvCxqkHT4Jmz79U

  node-server:
    depends_on:
      - db
    ports:
      - 3000:3000
    image: lalamefine/asso-blog:latest
    restart: always
    environment:
      DATABASE_URL: mysql://asso-blog:JvvCxqkHT4Jmz79U@db:3306/asso-blog
      NODE_ENV: production

  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/certbot:/etc/nginx/certbot
      - ./docker/nginx:/etc/nginx/conf.d

# certbot certonly --standalone --agree-tos --renew-by-default --register-unsafely-without-email -d amc-creusot.ddns.net --config-dir docker/certbot
# openssl req -x509 -newkey rsa:4096 -keyout docker/certbot/live/amc-creusot.ddns.net/privkey.pem -out docker/certbot/live/amc-creusot.ddns.net/fullchain.pem -days 365 -nodes -subj "/C=FR/ST=France/L=Paris/O=AMC Creusot/OU=AMC Creusot/CN=amc-creusot.ddns.net"

